FROM docker.io/ruby:3.4.0-preview1-alpine3.20

# Add support for nio4r, a transitive dependency from puma
RUN apt-get update
RUN apt-get install -y build-essential wget
# RUN apk update && apk upgrade --available && apk add build-base ruby-dev linux-headers make

# throw errors if Gemfile has been modified since Gemfile.lock
# RUN bundle config --global frozen 1

WORKDIR /app
COPY . .

RUN bundle install

EXPOSE 3000

ENTRYPOINT ["sh", "scripts/entrypoint.sh"]
