#!/bin/bash

#
# PRIVATE
#

function _noop {
    echo "Not implemented yet"
}

#
# PUBLIC
#

function enable-dev-cert {
    mkcert -install
}

function disable-dev-cert {
    mkcert -uninstall
}

function generate-dev-cert {
    mkcert -cert-file ./tools/proxy/contents/ssl/test.crt --key-file ./tools/proxy/contents/ssl/test.key tech.web4humans.com

    env bash tools/make-dev-cert.sh
}

function remove-dev-cert {
    rm ./tools/proxy/contents/ssl/*
}

function start-dev-server {
    OWNER_PASSWORD="${OWNER_PASSWORD}" HOME_DIR=`pwd` bundle exec guard -i
}


function help {
    echo "$0 <task> <args>"
    echo "Runs the tasks listed below."
    echo "To find out more about them, either read the source"
    echo "for ${0} or the docs located in 'docs/tasks.md'."
    echo "Tasks:"
    # Note that this omits private functions - those prefixed with an _
    compgen -A function | grep -e '^[^_]' | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
